app:
    resource: '@AppBundle/Controller/'
    type: annotation

igor:
    path: /igor
    defaults:
        _controller: FrameworkBundle:Template:template
        template: igor/index.html.twig

lucian-olariu:
    path: /lucian-olariu
    defaults:
        _controller: FrameworkBundle:Template:template
        template: lucian-olariu/index.html.twig
