app:
    resource: '@AppBundle/Controller/'
    type: annotation

igor:
    path: /igor
    defaults:
        _controller: FrameworkBundle:Template:template
        template: igor/index.html.twig

danet:
    path: /DanetMihai
    defaults:
        _controller: FrameworkBundle:Template:template
        template:  Danet/DanetMihai.html.twig

oancea:
    path: /oancea
    defaults:
        _controller: FrameworkBundle:Template:template
        template: oancea/index.html.twig
        
dogaru:
    path: /dogaru
    defaults:
        _controller: FrameworkBundle:Template:template
        template: dogaru/index.html.twig

lucian-olariu:
    path: /lucian-olariu
    defaults:
        _controller: FrameworkBundle:Template:template
        template: lucian-olariu/index.html.twig
        
alex-preda:
    path: /alex-preda
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Alex/index.html.twig
